# Copyright (C) 2019 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/asus/I01WD/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/asus/I01WD/proprietary/bin/dpmd:system/bin/dpmd \
    vendor/asus/I01WD/proprietary/etc/dpm/dpm.conf:system/etc/dpm/dpm.conf \
    vendor/asus/I01WD/proprietary/etc/init/dpmd.rc:system/etc/init/dpmd.rc \
    vendor/asus/I01WD/proprietary/etc/permissions/cneapiclient.xml:system/etc/permissions/cneapiclient.xml \
    vendor/asus/I01WD/proprietary/etc/permissions/com.qti.dpmframework.xml:system/etc/permissions/com.qti.dpmframework.xml \
    vendor/asus/I01WD/proprietary/etc/permissions/com.qti.location.sdk.xml:system/etc/permissions/com.qti.location.sdk.xml \
    vendor/asus/I01WD/proprietary/etc/permissions/com.qualcomm.location.xml:system/etc/permissions/com.qualcomm.location.xml \
    vendor/asus/I01WD/proprietary/etc/permissions/com.quicinc.cne.xml:system/etc/permissions/com.quicinc.cne.xml \
    vendor/asus/I01WD/proprietary/etc/permissions/dpmapi.xml:system/etc/permissions/dpmapi.xml \
    vendor/asus/I01WD/proprietary/etc/permissions/izat.xt.srv.xml:system/etc/permissions/izat.xt.srv.xml \
    vendor/asus/I01WD/proprietary/etc/permissions/privapp-permissions-com.qualcomm.location.xml:system/etc/permissions/privapp-permissions-com.qualcomm.location.xml \
    vendor/asus/I01WD/proprietary/etc/permissions/privapp-permissions-qti.xml:system/etc/permissions/privapp-permissions-qti.xml \
    vendor/asus/I01WD/proprietary/etc/permissions/qcrilhook.xml:system/etc/permissions/qcrilhook.xml \
    vendor/asus/I01WD/proprietary/etc/permissions/qti_libpermissions.xml:system/etc/permissions/qti_libpermissions.xml \
    vendor/asus/I01WD/proprietary/etc/permissions/qti_permissions.xml:system/etc/permissions/qti_permissions.xml \
    vendor/asus/I01WD/proprietary/etc/permissions/telephonyservice.xml:system/etc/permissions/telephonyservice.xml \
    vendor/asus/I01WD/proprietary/etc/sysconfig/qti_whitelist.xml:system/etc/sysconfig/qti_whitelist.xml \
    vendor/asus/I01WD/proprietary/framework/QtiTelephonyServicelibrary.jar:system/framework/QtiTelephonyServicelibrary.jar \
    vendor/asus/I01WD/proprietary/framework/cneapiclient.jar:system/framework/cneapiclient.jar \
    vendor/asus/I01WD/proprietary/framework/com.qti.dpmframework.jar:system/framework/com.qti.dpmframework.jar \
    vendor/asus/I01WD/proprietary/framework/com.qti.location.sdk.jar:system/framework/com.qti.location.sdk.jar \
    vendor/asus/I01WD/proprietary/framework/com.quicinc.cne.api-V1.0-java.jar:system/framework/com.quicinc.cne.api-V1.0-java.jar \
    vendor/asus/I01WD/proprietary/framework/com.quicinc.cne.api-V1.1-java.jar:system/framework/com.quicinc.cne.api-V1.1-java.jar \
    vendor/asus/I01WD/proprietary/framework/com.quicinc.cne.constants-V1.0-java.jar:system/framework/com.quicinc.cne.constants-V1.0-java.jar \
    vendor/asus/I01WD/proprietary/framework/com.quicinc.cne.constants-V2.0-java.jar:system/framework/com.quicinc.cne.constants-V2.0-java.jar \
    vendor/asus/I01WD/proprietary/framework/com.quicinc.cne.constants-V2.1-java.jar:system/framework/com.quicinc.cne.constants-V2.1-java.jar \
    vendor/asus/I01WD/proprietary/framework/com.quicinc.cne.jar:system/framework/com.quicinc.cne.jar \
    vendor/asus/I01WD/proprietary/framework/com.quicinc.cne.server-V1.0-java.jar:system/framework/com.quicinc.cne.server-V1.0-java.jar \
    vendor/asus/I01WD/proprietary/framework/com.quicinc.cne.server-V2.0-java.jar:system/framework/com.quicinc.cne.server-V2.0-java.jar \
    vendor/asus/I01WD/proprietary/framework/com.quicinc.cne.server-V2.1-java.jar:system/framework/com.quicinc.cne.server-V2.1-java.jar \
    vendor/asus/I01WD/proprietary/framework/com.quicinc.cne.server-V2.2-java.jar:system/framework/com.quicinc.cne.server-V2.2-java.jar \
    vendor/asus/I01WD/proprietary/framework/com.quicinc.cne.server-V2.3-java.jar:system/framework/com.quicinc.cne.server-V2.3-java.jar \
    vendor/asus/I01WD/proprietary/framework/dpmapi.jar:system/framework/dpmapi.jar \
    vendor/asus/I01WD/proprietary/framework/izat.xt.srv.jar:system/framework/izat.xt.srv.jar \
    vendor/asus/I01WD/proprietary/framework/qcrilhook.jar:system/framework/qcrilhook.jar \
    vendor/asus/I01WD/proprietary/framework/qti-telephony-common.jar:system/framework/qti-telephony-common.jar \
    vendor/asus/I01WD/proprietary/framework/tcmclient.jar:system/framework/tcmclient.jar \
    vendor/asus/I01WD/proprietary/framework/vendor.qti.hardware.data.latency-V1.0-java.jar:system/framework/vendor.qti.hardware.data.latency-V1.0-java.jar \
    vendor/asus/I01WD/proprietary/framework/vendor.qti.hardware.data.qmi-V1.0-java.jar:system/framework/vendor.qti.hardware.data.qmi-V1.0-java.jar \
    vendor/asus/I01WD/proprietary/lib/DataSet/ispDB/ASUS_UNDI.bin:system/lib/DataSet/ispDB/ASUS_UNDI.bin \
    vendor/asus/I01WD/proprietary/lib/com.qualcomm.qti.ant@1.0.so:system/lib/com.qualcomm.qti.ant@1.0.so \
    vendor/asus/I01WD/proprietary/lib/com.qualcomm.qti.dpm.api@1.0.so:system/lib/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/asus/I01WD/proprietary/lib/com.quicinc.cne.server@1.0.so:system/lib/com.quicinc.cne.server@1.0.so \
    vendor/asus/I01WD/proprietary/lib/com.quicinc.cne.server@2.3.so:system/lib/com.quicinc.cne.server@2.3.so \
    vendor/asus/I01WD/proprietary/lib/fm_helium.so:system/lib/fm_helium.so \
    vendor/asus/I01WD/proprietary/lib/libdpmctmgr.so:system/lib/libdpmctmgr.so \
    vendor/asus/I01WD/proprietary/lib/libdpmfdmgr.so:system/lib/libdpmfdmgr.so \
    vendor/asus/I01WD/proprietary/lib/libdpmframework.so:system/lib/libdpmframework.so \
    vendor/asus/I01WD/proprietary/lib/libdpmtcm.so:system/lib/libdpmtcm.so \
    vendor/asus/I01WD/proprietary/lib/libfm-hci.so:system/lib/libfm-hci.so \
    vendor/asus/I01WD/proprietary/lib/vendor.qti.hardware.data.latency@1.0.so:system/lib/vendor.qti.hardware.data.latency@1.0.so \
    vendor/asus/I01WD/proprietary/lib64/com.qualcomm.qti.ant@1.0.so:system/lib64/com.qualcomm.qti.ant@1.0.so \
    vendor/asus/I01WD/proprietary/lib64/com.qualcomm.qti.dpm.api@1.0.so:system/lib64/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/asus/I01WD/proprietary/lib64/com.quicinc.cne.server@1.0.so:system/lib64/com.quicinc.cne.server@1.0.so \
    vendor/asus/I01WD/proprietary/lib64/com.quicinc.cne.server@2.3.so:system/lib64/com.quicinc.cne.server@2.3.so \
    vendor/asus/I01WD/proprietary/lib64/fm_helium.so:system/lib64/fm_helium.so \
    vendor/asus/I01WD/proprietary/lib64/lib-imsvideocodec.so:system/lib64/lib-imsvideocodec.so \
    vendor/asus/I01WD/proprietary/lib64/lib-imsvt.so:system/lib64/lib-imsvt.so \
    vendor/asus/I01WD/proprietary/lib64/lib-imsvtextutils.so:system/lib64/lib-imsvtextutils.so \
    vendor/asus/I01WD/proprietary/lib64/lib-imsvtutils.so:system/lib64/lib-imsvtutils.so \
    vendor/asus/I01WD/proprietary/lib64/libAsusMotorDriverHAL.so:system/lib64/libAsusMotorDriverHAL.so \
    vendor/asus/I01WD/proprietary/lib64/libAsusRGBSensorHAL.so:system/lib64/libAsusRGBSensorHAL.so \
    vendor/asus/I01WD/proprietary/lib64/libaptXHD_encoder.so:system/lib64/libaptXHD_encoder.so \
    vendor/asus/I01WD/proprietary/lib64/libaptX_encoder.so:system/lib64/libaptX_encoder.so \
    vendor/asus/I01WD/proprietary/lib64/libdiag_system.so:system/lib64/libdiag_system.so \
    vendor/asus/I01WD/proprietary/lib64/libdpmctmgr.so:system/lib64/libdpmctmgr.so \
    vendor/asus/I01WD/proprietary/lib64/libdpmfdmgr.so:system/lib64/libdpmfdmgr.so \
    vendor/asus/I01WD/proprietary/lib64/libdpmframework.so:system/lib64/libdpmframework.so \
    vendor/asus/I01WD/proprietary/lib64/libdpmtcm.so:system/lib64/libdpmtcm.so \
    vendor/asus/I01WD/proprietary/lib64/libfm-hci.so:system/lib64/libfm-hci.so \
    vendor/asus/I01WD/proprietary/lib64/libimscamera_jni.so:system/lib64/libimscamera_jni.so \
    vendor/asus/I01WD/proprietary/lib64/libimsmedia_jni.so:system/lib64/libimsmedia_jni.so \
    vendor/asus/I01WD/proprietary/lib64/liblocationservice_jni.so:system/lib64/liblocationservice_jni.so \
    vendor/asus/I01WD/proprietary/lib64/librcc.so:system/lib64/librcc.so \
    vendor/asus/I01WD/proprietary/lib64/libxt_native.so:system/lib64/libxt_native.so \
    vendor/asus/I01WD/proprietary/lib64/vendor.qti.gnss@1.0.so:system/lib64/vendor.qti.gnss@1.0.so \
    vendor/asus/I01WD/proprietary/lib64/vendor.qti.gnss@1.1.so:system/lib64/vendor.qti.gnss@1.1.so \
    vendor/asus/I01WD/proprietary/lib64/vendor.qti.gnss@1.2.so:system/lib64/vendor.qti.gnss@1.2.so \
    vendor/asus/I01WD/proprietary/lib64/vendor.qti.gnss@2.0.so:system/lib64/vendor.qti.gnss@2.0.so \
    vendor/asus/I01WD/proprietary/lib64/vendor.qti.gnss@2.1.so:system/lib64/vendor.qti.gnss@2.1.so \
    vendor/asus/I01WD/proprietary/lib64/vendor.qti.hardware.data.latency@1.0.so:system/lib64/vendor.qti.hardware.data.latency@1.0.so \
    vendor/asus/I01WD/proprietary/lib64/vendor.qti.imsrtpservice@1.0.so:system/lib64/vendor.qti.imsrtpservice@1.0.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusCamera/lib/arm64/libUndistort.so:system/priv-app/AsusCamera/lib/arm64/libUndistort.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusCamera/lib/arm64/libarcsoft_object_tracking.so:system/priv-app/AsusCamera/lib/arm64/libarcsoft_object_tracking.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusCamera/lib/arm64/libarcsoft_panorama_burstcapture.so:system/priv-app/AsusCamera/lib/arm64/libarcsoft_panorama_burstcapture.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusCamera/lib/arm64/libarcsoft_undistort.so:system/priv-app/AsusCamera/lib/arm64/libarcsoft_undistort.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusCamera/lib/arm64/libasus_camera_object_tracking.so:system/priv-app/AsusCamera/lib/arm64/libasus_camera_object_tracking.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusCamera/lib/arm64/libasus_camera_panorama.so:system/priv-app/AsusCamera/lib/arm64/libasus_camera_panorama.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusCamera/lib/arm64/libasus_camera_selfiepano.so:system/priv-app/AsusCamera/lib/arm64/libasus_camera_selfiepano.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusCamera/lib/arm64/libasusundistort.so:system/priv-app/AsusCamera/lib/arm64/libasusundistort.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusCamera/lib/arm64/libbitmap.so:system/priv-app/AsusCamera/lib/arm64/libbitmap.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusCamera/lib/arm64/libmpbase.so:system/priv-app/AsusCamera/lib/arm64/libmpbase.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusCamera/lib/arm64/libtensorflowlite_jni.so:system/priv-app/AsusCamera/lib/arm64/libtensorflowlite_jni.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusCamera/lib/arm64/libyuv_util.so:system/priv-app/AsusCamera/lib/arm64/libyuv_util.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/libRSSupport.so:system/priv-app/AsusGallery/lib/arm/libRSSupport.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/libarcsoft_beautyshot.so:system/priv-app/AsusGallery/lib/arm/libarcsoft_beautyshot.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/libarcsoft_undistort.so:system/priv-app/AsusGallery/lib/arm/libarcsoft_undistort.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/libblur.so:system/priv-app/AsusGallery/lib/arm/libblur.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/libcvface_api.so:system/priv-app/AsusGallery/lib/arm/libcvface_api.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/libgif.so:system/priv-app/AsusGallery/lib/arm/libgif.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/libgvr.so:system/priv-app/AsusGallery/lib/arm/libgvr.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/libjni_cvface_api.so:system/priv-app/AsusGallery/lib/arm/libjni_cvface_api.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/libjni_face_effect.so:system/priv-app/AsusGallery/lib/arm/libjni_face_effect.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/libjni_filter_show.so:system/priv-app/AsusGallery/lib/arm/libjni_filter_show.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/libjni_wide_angle_undistort.so:system/priv-app/AsusGallery/lib/arm/libjni_wide_angle_undistort.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/libmpbase.so:system/priv-app/AsusGallery/lib/arm/libmpbase.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/libopencv_java3.so:system/priv-app/AsusGallery/lib/arm/libopencv_java3.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/libpano_video_renderer.so:system/priv-app/AsusGallery/lib/arm/libpano_video_renderer.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/libpanorenderer.so:system/priv-app/AsusGallery/lib/arm/libpanorenderer.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/librs.blur.so:system/priv-app/AsusGallery/lib/arm/librs.blur.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/librs.convolve3x3.so:system/priv-app/AsusGallery/lib/arm/librs.convolve3x3.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/librs.grad.so:system/priv-app/AsusGallery/lib/arm/librs.grad.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/librs.grey.so:system/priv-app/AsusGallery/lib/arm/librs.grey.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/librs.saturation.so:system/priv-app/AsusGallery/lib/arm/librs.saturation.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/librs.vignette.so:system/priv-app/AsusGallery/lib/arm/librs.vignette.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/librsjni.so:system/priv-app/AsusGallery/lib/arm/librsjni.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/librsjni_androidx.so:system/priv-app/AsusGallery/lib/arm/librsjni_androidx.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/libtensorflow_inference.so:system/priv-app/AsusGallery/lib/arm/libtensorflow_inference.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGallery/lib/arm/libtensorflowlite_jni.so:system/priv-app/AsusGallery/lib/arm/libtensorflowlite_jni.so \
    vendor/asus/I01WD/proprietary/priv-app/AsusGalleryBurst/lib/arm/libgifencoder.so:system/priv-app/AsusGalleryBurst/lib/arm/libgifencoder.so \
    vendor/asus/I01WD/proprietary/priv-app/MotorService/lib/arm64/libAsusLaserSensorHAL.so:system/priv-app/MotorService/lib/arm64/libAsusLaserSensorHAL.so \
    vendor/asus/I01WD/proprietary/priv-app/MotorService/lib/arm64/libAsusMotorDriverHAL.so:system/priv-app/MotorService/lib/arm64/libAsusMotorDriverHAL.so \
    vendor/asus/I01WD/proprietary/priv-app/MotorService/lib/arm64/libjni_laser.so:system/priv-app/MotorService/lib/arm64/libjni_laser.so \
    vendor/asus/I01WD/proprietary/priv-app/MotorService/lib/arm64/libjni_motor.so:system/priv-app/MotorService/lib/arm64/libjni_motor.so

PRODUCT_PACKAGES += \
    libantradio \
    vendor.qti.hardware.fm@1.0 \
    QtiTelephonyService \
    aptxals \
    CNEService \
    HotwordEnrollmentOKGoogleWCD9340 \
    HotwordEnrollmentXGoogleWCD9340 \
    AsusCamera \
    AsusGallery \
    AsusGalleryBurst \
    MotorService \
    com.qualcomm.location \
    dpmserviceapp \
    ims \
    qcrilmsgtunnel
